version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'fakeoai'
      MYSQL_DATABASE: 'tokens'

  redis:
    image: redis
    container_name: redis
    command: --requirepass "fakeoai" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/:/data/

  warp: # 请勿修改此服务的任何配置
    image: caomingjun/warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp

  tokens:
    image: fakeoai/tokens
    container_name: tokens
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8000:8000
    volumes:
      - ./config:/app/config
      - ./keys:/app/keys
      - ./logs:/app/logs
    depends_on:
      - redis
      - mysql
      - warp
