version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'tokens'

  redis:
    image: redis
    container_name: redis
    # command: --requirepass "123456" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/:/data/

  tokens:
    image: fakeoai/tokens
    container_name: tokens
    restart: always
    network_mode: 'host'
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8000:8000
    volumes:
      - ./config:/app/config
      - ./keys:/app/keys
      - ./logs:/app/logs
    depends_on:
      - redis
      - mysql