server:
  address: :8000 # 项目http端口
  # httpsAddr: :443 # 项目https端口
  # httpsCertPath: keys/ssl.pem # ssl证书公钥地址
  # httpsKeyPath: keys/ssl.key # ssl证书私钥地址
  adminPath: / # 自定义后台访问地址的前缀
  logPath: logs
  logStdout: false

database:
  default:
    link: mysql:root:fakeoai@tcp(mysql:3306)/tokens?loc=Local&parseTime=true
    charset: utf8mb4

redis:
  default:
    address: redis:6379
    pass: fakeoai
    db: 0